spring:
  application:
    name: recipe-service
  grpc:
    server:
      port: 6565

# Optional: standard HTTP server (Spring Boot) port â€” set to 0 to disable if only gRPC is needed
server:
  port: 8080

