spring:
  application:
    name: recipe-api-grpc
  grpc:
    server:
      port: 50051
      reflection:
        enabled: true
  flyway:
    enabled: true
    locations: classpath:recipe/migration
    baseline-on-migrate: true
    baseline-version: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
