spring:
  application:
    name: recipe-auth-api-grpc
  grpc:
    server:
      port: 50054
      reflection:
        enabled: true
  flyway:
    enabled: true
    locations: classpath:auth/migration
    baseline-on-migrate: true
    baseline-version: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    key:
      private: classpath:keys/private.pem
      public: classpath:keys/public.pem