spring:
  application:
    name: recipe-gateway

  grpc:
    client:
      default-channel:
        address: static://localhost:50054
        negotiation-type: plaintext
      channels:
        recipe-service:
          address: static://localhost:50051
          negotiation-type: plaintext
          enable-keep-alive: true
          keep-alive-time: 30s
          keep-alive-timeout: 10s
          keep-alive-without-calls: true



server:
  port: 8081
