spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  application:
    name: recipe-gateway
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: 4d7525e78827173ea7718b0667293cbbd76857da6aa2f4d4f267044d762de580

springdoc:
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  client:
    recipe-service:
      address: static://localhost:50051
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-without-calls: true
    recipe-auth-service:
      address: static://localhost:50054
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: true

server:
  port: 8081

#logging:
#  level:
#    root: INFO
#    org.springframework.security: TRACE